name: frontend
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.15.3
  firebase_auth_web: ^5.7.3
  google_sign_in: ^6.1.0

  # HTTP & file upload
  http: any
  http_parser: any

  # Image picker
  image_picker: ^0.8.7+4

  # Cupertino icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
